name: Terraform Plan

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Application Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infrastructure/application

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::194772391548:role/api-monitoring-portal-github-actions-role
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.4"

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -no-color
        